"""Stratify the one-step decision by time-to-paddle-contact (read-only probe on frozen checkpoints).

For each cloned state: root RAM (ball_x 99, ball_y 101, paddle_x 72, ball vy from the previous
decision), then for every action the REAL successor (critic = r + g max Q(f(x'_a))) and the MODEL
successor (planner = r_hat + g c_hat max Q(g(z,a))). Monte-Carlo ground truth (60 decisions of the
arm's own eps-0.05 Q policy, shared RNG) for the contact-imminent stratum and a subsample of far states.
"""
import json
import sys

import numpy as np
import torch

from atari_jepa.checkpoint import check_compatible, load_checkpoint, model_from_checkpoint
from atari_jepa.envs import FrameStacker, make_env
from atari_jepa.losses import cosine_distance, expected_reward
from atari_jepa.planning import one_step_scores

EPS, H, EVERY, TARGET = 0.05, 60, 2, 700
BEHAVIOUR = "planner"  # states are generated by the H=1 planner; MC continuation stays the actor
PADDLE_Y = 179  # ball_y at which vy flips on a paddle contact (measured 177-181)
MC_IMM, MC_FAR = 90, 45


def kendall(a, b):
    n, s = len(a), 0
    for i in range(n):
        for j in range(i + 1, n):
            s += np.sign(a[i] - a[j]) * np.sign(b[i] - b[j])
    return s / (n * (n - 1) / 2)


@torch.no_grad()
def policy_action(model, history, device, rng, A):
    z = model.encoder(torch.from_numpy(history).to(device).unsqueeze(0))
    a = int(model.q_head(z).argmax(-1))
    return int(rng.integers(A)) if rng.random() < EPS else a


@torch.no_grad()
def mc_return(env, model, stacker, history, first_action, device, A, gamma, seed):
    rng = np.random.default_rng(seed)
    hist = history.copy()
    total, disc = 0.0, 1.0
    obs, r, term, trunc, _ = env.step(first_action)
    total += disc * float(np.sign(r)); disc *= gamma
    hist = np.concatenate([hist[1:], obs[None]], 0)
    if term or trunc:
        return total
    for _ in range(H - 1):
        a = policy_action(model, hist, device, rng, A)
        obs, r, term, trunc, _ = env.step(a)
        total += disc * float(np.sign(r)); disc *= gamma
        hist = np.concatenate([hist[1:], obs[None]], 0)
        if term or trunc:
            break
    return total


def stratum_of(by, vy):
    if by == 0 or vy is None or vy == 0:
        return "noball", None
    if vy > 0:
        ttc = (PADDLE_Y - by) / vy
        if ttc <= 2.5:
            return "imminent", ttc
        if ttc <= 6:
            return "near", ttc
        return "far_down", ttc
    return ("postcontact" if by >= 160 else "up"), None


@torch.no_grad()
def run(name, seed):
    device = torch.device("cuda")
    d = f"runs/{name}/seed{seed}"
    ckpt = load_checkpoint(f"{d}/checkpoint.pt", device)
    cfg, model = model_from_checkpoint(ckpt, device)
    model.eval()
    env = make_env(cfg.env)
    check_compatible(ckpt["env"], env.metadata())
    stacker = FrameStacker(cfg.env.history)
    A, g = env.num_actions, cfg.loss.gamma
    acts = torch.arange(A, device=device)
    rng = np.random.default_rng(51_000 + seed)
    rows, n_mc = [], {"imminent": 0, "far": 0}
    ep = 0
    while len(rows) < TARGET and ep < 12:
        obs, _ = env.reset(seed=51_000 + seed * 10 + ep)
        history = stacker.reset(obs)
        prev_by = None
        for t in range(2500):
            ram = env.state_vector()
            bx, by, px = int(ram[99]), int(ram[101]), int(ram[72])
            vy = None if (prev_by is None or by == 0 or prev_by == 0) else by - prev_by
            if t % EVERY == 0 and len(rows) < TARGET:
                snap = env.clone_state()
                succ, real_r, succ_by = [], np.zeros(A), []
                for a in range(A):
                    env.restore_state(snap)
                    nxt, r, _, _, _ = env.step(a)
                    succ.append(np.concatenate([history[1:], nxt[None]], 0)); real_r[a] = np.sign(r)
                    succ_by.append(int(env.state_vector()[101]))
                env.restore_state(snap)
                z = model.encoder(torch.from_numpy(history).to(device).unsqueeze(0))
                q_root = model.q_head(z)[0].cpu().numpy()
                z_true = model.encoder(torch.from_numpy(np.stack(succ)).to(device))
                v_true = model.q_head(z_true).max(-1).values.cpu().numpy()
                critic = real_r + g * v_true
                zr = z.expand(A, *z.shape[1:])
                z_pred = model.dynamics(zr, acts)
                r_hat = expected_reward(model.reward_head(zr, acts)).cpu().numpy()
                c_hat = torch.sigmoid(model.continuation_head(zr, acts)).cpu().numpy()
                v_pred = model.q_head(z_pred).max(-1).values.cpu().numpy()
                model_v = r_hat + g * c_hat * v_pred
                cos_pt = cosine_distance(z_pred, z_true).cpu().numpy()
                cos_root_true = cosine_distance(z.expand_as(z_true), z_true).cpu().numpy()
                stratum, ttc = stratum_of(by, vy)
                want_mc = (stratum == "imminent" and n_mc["imminent"] < MC_IMM) or (
                    stratum in ("far_down", "up") and n_mc["far"] < MC_FAR and rng.random() < 0.3)
                mc = None
                if want_mc:
                    mc = np.zeros(A)
                    for a in range(A):
                        env.restore_state(snap)
                        mc[a] = mc_return(env, model, stacker, history, a, device, A, g, seed=len(rows) * 7 + 1)
                    env.restore_state(snap)
                    n_mc["imminent" if stratum == "imminent" else "far"] += 1
                rows.append({
                    "stratum": stratum, "ttc": ttc, "bx": bx, "by": by, "px": px, "vy": vy,
                    "q_root": q_root.tolist(), "critic": critic.tolist(), "model": model_v.tolist(),
                    "v_true": v_true.tolist(), "v_pred": v_pred.tolist(), "real_r": real_r.tolist(),
                    "cos_pred_true": cos_pt.tolist(), "cos_root_true": cos_root_true.tolist(),
                    "succ_by": succ_by, "mc": None if mc is None else mc.tolist(),
                })
            if BEHAVIOUR == "planner":
                zb = model.encoder(torch.from_numpy(history).to(device).unsqueeze(0))
                action = int(one_step_scores(model, zb, g).argmax(-1))
                if rng.random() < EPS:
                    action = int(rng.integers(A))
            else:
                action = policy_action(model, history, device, rng, A)
            obs, _, term, trunc, _ = env.step(action)
            history = stacker.push(obs)
            prev_by = by
            if term or trunc:
                break
        ep += 1
    env.close()
    return {"K": cfg.replay.rollout_steps, "rows": rows}


def summarize(name, rows):
    strata = ["imminent", "near", "far_down", "up", "postcontact", "noball"]
    out = {}
    for s in strata:
        rs = [r for r in rows if r["stratum"] == s]
        if not rs:
            continue
        crit = np.array([r["critic"] for r in rs]); mod = np.array([r["model"] for r in rs])
        act = np.array([r["q_root"] for r in rs])
        agree_mc = np.mean([np.argmax(r["model"]) == np.argmax(r["critic"]) for r in rs])
        agree_ac = np.mean([np.argmax(r["q_root"]) == np.argmax(r["critic"]) for r in rs])
        tau_mc = np.mean([kendall(r["model"], r["critic"]) for r in rs])
        tau_ac = np.mean([kendall(r["q_root"], r["critic"]) for r in rs])
        rec = {
            "n": len(rs),
            "range_critic": float(np.mean(crit.max(1) - crit.min(1))),
            "range_model": float(np.mean(mod.max(1) - mod.min(1))),
            "range_actor": float(np.mean(act.max(1) - act.min(1))),
            "argmax_model_eq_critic": float(agree_mc), "argmax_actor_eq_critic": float(agree_ac),
            "tau_model_critic": float(tau_mc), "tau_actor_critic": float(tau_ac),
            "cos_pred_true": float(np.mean([np.mean(r["cos_pred_true"]) for r in rs])),
            "cos_root_true": float(np.mean([np.mean(r["cos_root_true"]) for r in rs])),
        }
        mcs = [r for r in rs if r["mc"] is not None and (max(r["mc"]) - min(r["mc"])) > 1e-9]
        if mcs:
            rec["mc_n_decisive"] = len(mcs)
            rec["mc_n_total"] = sum(1 for r in rs if r["mc"] is not None)
            rec["mc_spread"] = float(np.mean([max(r["mc"]) - min(r["mc"]) for r in mcs]))
            for key in ("q_root", "critic", "model"):
                rec[f"mc_tau_{key}"] = float(np.mean([kendall(r["mc"], r[key]) for r in mcs]))
                rec[f"mc_regret_{key}"] = float(np.mean([r["mc"][int(np.argmax(r[key]))] - max(r["mc"]) for r in mcs]))
        out[s] = rec
    return out


if __name__ == "__main__":
    names = sys.argv[1:]
    result = {}
    for name in names:
        allrows = []
        per_seed = {}
        for s in range(3):
            try:
                r = run(name, s)
            except FileNotFoundError:
                continue
            per_seed[s] = summarize(name, r["rows"])
            allrows += r["rows"]
            print(f"{name} seed{s}: {len(r['rows'])} rows, strata:",
                  {k: v["n"] for k, v in per_seed[s].items()}, flush=True)
        pooled = summarize(name, allrows)
        result[name] = {"pooled": pooled, "per_seed": per_seed}
        for s, rec in pooled.items():
            print(f"{name:26s} {s:12s} n={rec['n']:4d} rangeC {rec['range_critic']:.3f} rangeM {rec['range_model']:.3f} "
                  f"rangeA {rec['range_actor']:.3f} | argmax M=C {rec['argmax_model_eq_critic']:.2f} A=C {rec['argmax_actor_eq_critic']:.2f} "
                  f"| tau M-C {rec['tau_model_critic']:+.3f} A-C {rec['tau_actor_critic']:+.3f} | cosPT {rec['cos_pred_true']:.3f} cosRT {rec['cos_root_true']:.3f}"
                  + (f" | MC n={rec['mc_n_decisive']}/{rec['mc_n_total']} spread {rec['mc_spread']:.3f} regret A {rec['mc_regret_q_root']:+.3f} C {rec['mc_regret_critic']:+.3f} M {rec['mc_regret_model']:+.3f} tau A {rec['mc_tau_q_root']:+.3f} C {rec['mc_tau_critic']:+.3f} M {rec['mc_tau_model']:+.3f}" if "mc_n_decisive" in rec else ""),
                  flush=True)
    print("JSON_BEGIN")
    print(json.dumps(result))
    print("JSON_END")
